### ISSUE TITLE
[TASK] Apply workspace lints globally

### ISSUE THREAD

**Issue by Serial-ATA** [tangle-network/blueprint#701]
# Overview

Right now, only some crates have:

```toml
[lints]
workspace = true
```

in their manifests.

Doing it all at once will probably cause a decent amount of errors, may need to break it up.
